blueprint:
  name: Human Detection via LLMVision @Fahad0x1
  description: >
    Sends a rich notification when a person or human is detected in the camera
    feed analyzed by LLMVision. 
  domain: automation
  input:
    notify_device:
      name: Notify Device
      description: Mobile device to send notification
      selector:
        device:
          integration: mobile_app
    llm_provider_id:
      name: LLMVision Provider ID
      description: Found in your LLMVision config
      default: 01JY23JDQ7AKF4XA6F7FXN3FCZ
      selector:
        text:
    lovelace_view:
      name: Lovelace View
      description: Where notification should open on click
      default: /lovelace/0
      selector:
        text:

trigger:
  - platform: event
    event_type: llmvision.analysis_result

condition:
  - condition: template
    value_template: >
      {{ trigger.event.data.provider == llm_provider_id and
         ("person" in trigger.event.data.response_text | lower or
          "human" in trigger.event.data.response_text | lower) }}

action:
  - variables:
      notify_service: >
        {% set device = device_attr(notify_device, "name") %}
        {{ "notify.mobile_app_" ~ device | slugify }}
      image_url: >
        {{ trigger.event.data.key_frame.replace("/config/www/", "/local/") if trigger.event.data.key_frame else "" }}

  - service: "{{ notify_service }}"
    data:
      title: "{{ trigger.event.data.title or 'Human Detected' }}"
      message: "{{ trigger.event.data.response_text }}"
      data:
        image: "{{ image_url }}"
        tag: "llmvision-alert"
        group: "llmvision"
        ttl: 0
        priority: high
        channel: "LLMVision Alerts"
        clickAction: "{{ lovelace_view }}"
        sticky: true
        notification_icon: mdi:account
        color: "#03a9f4"
        push:
          interruption-level: active

mode: single
